// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAofoRVsAF3E1opw5_pJVRNbyXcCkG0C_A',
    appId: '1:817062521480:web:7ab7c983f8340d78bc0d3d',
    messagingSenderId: '817062521480',
    projectId: 'flutterreviewemployes',
    authDomain: 'flutterreviewemployes.firebaseapp.com',
    storageBucket: 'flutterreviewemployes.appspot.com',
    measurementId: 'G-LDQYFSJ10V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn4hqSUxR0gbmw81uf6gXkWSggE_mvTRQ',
    appId: '1:817062521480:android:6f884ac25e7b0ee5bc0d3d',
    messagingSenderId: '817062521480',
    projectId: 'flutterreviewemployes',
    storageBucket: 'flutterreviewemployes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT1flehC3xnQinDFyEKWELGJhf2DOusj0',
    appId: '1:817062521480:ios:00e57b9f4fb0c480bc0d3d',
    messagingSenderId: '817062521480',
    projectId: 'flutterreviewemployes',
    storageBucket: 'flutterreviewemployes.appspot.com',
    androidClientId: '817062521480-7vi01p28839aqrbgbiaoif95guff61dm.apps.googleusercontent.com',
    iosClientId: '817062521480-g46qba93s0potaqjr132q7kg75ekaia0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviewMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT1flehC3xnQinDFyEKWELGJhf2DOusj0',
    appId: '1:817062521480:ios:00e57b9f4fb0c480bc0d3d',
    messagingSenderId: '817062521480',
    projectId: 'flutterreviewemployes',
    storageBucket: 'flutterreviewemployes.appspot.com',
    androidClientId: '817062521480-7vi01p28839aqrbgbiaoif95guff61dm.apps.googleusercontent.com',
    iosClientId: '817062521480-g46qba93s0potaqjr132q7kg75ekaia0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviewMe',
  );
}
